[GENERAL]
DATA_DIR = "/scratch/data"

[SPLIT]
SENSOR = "s2"
TILE_SHAPE = [256, 256]
IMG_BANDS_IDX = [0, 1, 2, 3, 4, 5]
SLOPE = true
EXCLUDE_NODATA = true
OUT_DIR = "/scratch/tiles"

[AUGMENT]
IMG_DIR = "/scratch/tiles/val/img"
MSK_DIR = "/scratch/tiles/val/msk"
NAUGS = 1
SLOPE_IN_BANDS = true